type StatusLog {
  id: ID!
  status: ShipmentStatus!
  location: String!
  note: String
  createdAt: String!
}

type Shipment {
  id: ID!
  trackingId: String!
  origin: String!
  destination: String!
  weight: Float!
  description: String
  status: ShipmentStatus!
  estimatedDate: String
  createdAt: String!
  updatedAt: String!
  statusLogs: [StatusLog!]!
  user: User!
}

input CreateShipmentInput {
  origin: String!
  destination: String!
  weight: Float!
  description: String
  estimatedDate: String
}

input UpdateStatusInput {
  shipmentId: ID!
  status: ShipmentStatus!
  location: String!
  note: String
}

extend type Query {
  shipments: [Shipment!]!
  shipment(id: ID!): Shipment
  trackShipment(trackingId: String!): Shipment
}

extend type Mutation {
  createShipment(input: CreateShipmentInput!): Shipment!
  updateShipmentStatus(input: UpdateStatusInput!): Shipment!
  cancelShipment(id: ID!): Shipment!
}