import { LocationType } from "../src/generated/prisma";
import { prisma } from "../src/lib/prisma";
import { redis } from "../src/lib/redis";

export interface SeedLocation {
    name: string;
    code: string;
    country: string;
    countryCode: string;
    city: string;
    region: string;
    latitude: number;
    longitude: number;
    type: LocationType;
}

export const genuineLocations: SeedLocation[] = [
    // ─── BANGLADESH (12) ───────────────────────────────────────
    {
        name: "Port of Chittagong (Chattogram)",
        code: "BDCGP",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Chittagong",
        region: "Chittagong Division",
        latitude: 22.3167,
        longitude: 91.8000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Mongla",
        code: "BDMGL",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Mongla",
        region: "Khulna Division",
        latitude: 22.4936,
        longitude: 89.5936,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Payra Deep Sea Port",
        code: "BDPAY",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Kalapara",
        region: "Barisal Division",
        latitude: 21.9908,
        longitude: 90.2800,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Matarbari Deep Sea Port",
        code: "BDMTB",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Maheshkhali",
        region: "Chittagong Division",
        latitude: 21.7000,
        longitude: 91.8700,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Hazrat Shahjalal International Airport Cargo Terminal",
        code: "DAC",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Dhaka",
        region: "Dhaka Division",
        latitude: 23.8433,
        longitude: 90.4029,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Shah Amanat International Airport Cargo",
        code: "CGP",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Chittagong",
        region: "Chittagong Division",
        latitude: 22.2496,
        longitude: 91.8133,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Osmani International Airport Cargo Terminal",
        code: "ZYL",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Sylhet",
        region: "Sylhet Division",
        latitude: 24.9632,
        longitude: 91.8668,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Kamalapur Inland Container Depot",
        code: "BDKML",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Dhaka",
        region: "Dhaka Division",
        latitude: 23.7317,
        longitude: 90.4253,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Pangaon Inland Container Terminal",
        code: "BDPCT",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Keraniganj",
        region: "Dhaka Division",
        latitude: 23.6702,
        longitude: 90.4352,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Benapole Land Port & Inland Container Yard",
        code: "BDBEN",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Sharsha",
        region: "Khulna Division",
        latitude: 23.0441,
        longitude: 88.8953,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Ishwardi Inland Container Depot",
        code: "BDISD",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Ishwardi",
        region: "Rajshahi Division",
        latitude: 24.1264,
        longitude: 89.0683,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Dhaka Customs Air Freight Terminal",
        code: "BDDAC-ICD",
        country: "Bangladesh",
        countryCode: "BD",
        city: "Dhaka",
        region: "Dhaka Division",
        latitude: 23.8500,
        longitude: 90.4100,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── SINGAPORE (4) ─────────────────────────────────────────
    {
        name: "Port of Singapore (Jurong & Pasir Panjang)",
        code: "SGSIN",
        country: "Singapore",
        countryCode: "SG",
        city: "Singapore",
        region: "South West",
        latitude: 1.2644,
        longitude: 103.8222,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Tuas Mega Port",
        code: "SGTUA",
        country: "Singapore",
        countryCode: "SG",
        city: "Singapore",
        region: "West Region",
        latitude: 1.2500,
        longitude: 103.6333,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Singapore Changi Air Cargo Complex",
        code: "SIN",
        country: "Singapore",
        countryCode: "SG",
        city: "Singapore",
        region: "East Region",
        latitude: 1.3644,
        longitude: 103.9915,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Keppel Distripark Logistics Hub",
        code: "SGKPL",
        country: "Singapore",
        countryCode: "SG",
        city: "Singapore",
        region: "Central Region",
        latitude: 1.2700,
        longitude: 103.8350,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── CHINA (18) ────────────────────────────────────────────
    {
        name: "Port of Shanghai (Yangshan Deepwater)",
        code: "CNSHA",
        country: "China",
        countryCode: "CN",
        city: "Shanghai",
        region: "East China",
        latitude: 30.6278,
        longitude: 122.0622,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Ningbo-Zhoushan",
        code: "CNNGB",
        country: "China",
        countryCode: "CN",
        city: "Ningbo",
        region: "Zhejiang",
        latitude: 29.8878,
        longitude: 121.5606,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Shenzhen (Yantian Container Terminal)",
        code: "CNYTN",
        country: "China",
        countryCode: "CN",
        city: "Shenzhen",
        region: "Guangdong",
        latitude: 22.5800,
        longitude: 114.2700,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Shenzhen (Shekou Port)",
        code: "CNSHK",
        country: "China",
        countryCode: "CN",
        city: "Shenzhen",
        region: "Guangdong",
        latitude: 22.4792,
        longitude: 113.9108,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Guangzhou (Nansha)",
        code: "CNGZU",
        country: "China",
        countryCode: "CN",
        city: "Guangzhou",
        region: "Guangdong",
        latitude: 22.7500,
        longitude: 113.6000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Qingdao",
        code: "CNTAO",
        country: "China",
        countryCode: "CN",
        city: "Qingdao",
        region: "Shandong",
        latitude: 36.0671,
        longitude: 120.3826,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Tianjin (Xingang)",
        code: "CNTSN",
        country: "China",
        countryCode: "CN",
        city: "Tianjin",
        region: "North China",
        latitude: 38.9833,
        longitude: 117.7500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Xiamen",
        code: "CNXMN",
        country: "China",
        countryCode: "CN",
        city: "Xiamen",
        region: "Fujian",
        latitude: 24.4842,
        longitude: 118.0678,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Dalian",
        code: "CNDLC",
        country: "China",
        countryCode: "CN",
        city: "Dalian",
        region: "Liaoning",
        latitude: 38.9285,
        longitude: 121.6547,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Shanghai Pudong International Cargo Hub",
        code: "PVG",
        country: "China",
        countryCode: "CN",
        city: "Shanghai",
        region: "East China",
        latitude: 31.1443,
        longitude: 121.8083,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Guangzhou Baiyun International Airport Cargo",
        code: "CAN",
        country: "China",
        countryCode: "CN",
        city: "Guangzhou",
        region: "Guangdong",
        latitude: 23.3924,
        longitude: 113.2988,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Shenzhen Bao'an Cargo Hub",
        code: "SZX",
        country: "China",
        countryCode: "CN",
        city: "Shenzhen",
        region: "Guangdong",
        latitude: 22.6393,
        longitude: 113.8107,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Beijing Capital International Airport Cargo",
        code: "PEK",
        country: "China",
        countryCode: "CN",
        city: "Beijing",
        region: "North China",
        latitude: 40.0799,
        longitude: 116.6031,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Chengdu Shuangliu Logistics Hub",
        code: "CTU-ICD",
        country: "China",
        countryCode: "CN",
        city: "Chengdu",
        region: "Sichuan",
        latitude: 30.5785,
        longitude: 103.9471,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Chongqing International Logistics Hub Park",
        code: "CKG-ICD",
        country: "China",
        countryCode: "CN",
        city: "Chongqing",
        region: "Southwest",
        latitude: 29.5630,
        longitude: 106.5516,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Wuhan Yangluo Inland Port & Logistics Depot",
        code: "WUH-ICD",
        country: "China",
        countryCode: "CN",
        city: "Wuhan",
        region: "Hubei",
        latitude: 30.6860,
        longitude: 114.5240,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Xi'an International Trade & Logistics Park",
        code: "XIY-ICD",
        country: "China",
        countryCode: "CN",
        city: "Xi'an",
        region: "Shaanxi",
        latitude: 34.3416,
        longitude: 108.9398,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Zhengzhou International Hub Inland Port",
        code: "CGO-ICD",
        country: "China",
        countryCode: "CN",
        city: "Zhengzhou",
        region: "Henan",
        latitude: 34.7466,
        longitude: 113.6253,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── HONG KONG & TAIWAN (5) ─────────────────────────────────
    {
        name: "Port of Hong Kong (Kwai Tsing)",
        code: "HKHKG",
        country: "Hong Kong",
        countryCode: "HK",
        city: "Hong Kong",
        region: "New Territories",
        latitude: 22.3500,
        longitude: 114.1167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Hong Kong International Airport SuperTerminal",
        code: "HKG",
        country: "Hong Kong",
        countryCode: "HK",
        city: "Hong Kong",
        region: "Chek Lap Kok",
        latitude: 22.3080,
        longitude: 113.9185,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Port of Kaohsiung",
        code: "TWKHH",
        country: "Taiwan",
        countryCode: "TW",
        city: "Kaohsiung",
        region: "Southern Taiwan",
        latitude: 22.6167,
        longitude: 120.2833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Keelung",
        code: "TWKEL",
        country: "Taiwan",
        countryCode: "TW",
        city: "Keelung",
        region: "Northern Taiwan",
        latitude: 25.1333,
        longitude: 121.7333,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Taiwan Taoyuan International Airport Air Cargo",
        code: "TPE",
        country: "Taiwan",
        countryCode: "TW",
        city: "Taoyuan",
        region: "Northern Taiwan",
        latitude: 25.0797,
        longitude: 121.2342,
        type: LocationType.AIR_PORT,
    },

    // ─── JAPAN (8) ─────────────────────────────────────────────
    {
        name: "Port of Tokyo (Ohi Container Terminal)",
        code: "JPTYO",
        country: "Japan",
        countryCode: "JP",
        city: "Tokyo",
        region: "Kanto",
        latitude: 35.6190,
        longitude: 139.7780,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Yokohama (Minami Honmoku Pier)",
        code: "JPYOK",
        country: "Japan",
        countryCode: "JP",
        city: "Yokohama",
        region: "Kanagawa",
        latitude: 35.4333,
        longitude: 139.6833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Kobe",
        code: "JPUKB",
        country: "Japan",
        countryCode: "JP",
        city: "Kobe",
        region: "Hyogo",
        latitude: 34.6833,
        longitude: 135.2000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Nagoya",
        code: "JPNGO",
        country: "Japan",
        countryCode: "JP",
        city: "Nagoya",
        region: "Aichi",
        latitude: 35.0833,
        longitude: 136.8833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Osaka",
        code: "JPOSA",
        country: "Japan",
        countryCode: "JP",
        city: "Osaka",
        region: "Kansai",
        latitude: 34.6500,
        longitude: 135.4333,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Tokyo Narita International Airport Cargo",
        code: "NRT",
        country: "Japan",
        countryCode: "JP",
        city: "Narita",
        region: "Chiba",
        latitude: 35.7720,
        longitude: 140.3929,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Kansai International Airport Cargo Hub",
        code: "KIX",
        country: "Japan",
        countryCode: "JP",
        city: "Osaka",
        region: "Kansai",
        latitude: 34.4342,
        longitude: 135.2327,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Tokyo Freight Terminal (Ohi Inland Depot)",
        code: "JP-TYO-ICD",
        country: "Japan",
        countryCode: "JP",
        city: "Tokyo",
        region: "Kanto",
        latitude: 35.5990,
        longitude: 139.7540,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── SOUTH KOREA (5) ───────────────────────────────────────
    {
        name: "Port of Busan (New Port)",
        code: "KRPUS",
        country: "South Korea",
        countryCode: "KR",
        city: "Busan",
        region: "Gyeongsang",
        latitude: 35.0833,
        longitude: 128.8333,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Incheon",
        code: "KRINC",
        country: "South Korea",
        countryCode: "KR",
        city: "Incheon",
        region: "Gyeonggi",
        latitude: 37.4500,
        longitude: 126.6167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Gwangyang",
        code: "KRKAN",
        country: "South Korea",
        countryCode: "KR",
        city: "Gwangyang",
        region: "Jeolla",
        latitude: 34.9080,
        longitude: 127.7000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Incheon International Airport Cargo Terminal",
        code: "ICN",
        country: "South Korea",
        countryCode: "KR",
        city: "Incheon",
        region: "Gyeonggi",
        latitude: 37.4602,
        longitude: 126.4407,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Uiwang Inland Container Depot",
        code: "KRUIW",
        country: "South Korea",
        countryCode: "KR",
        city: "Uiwang",
        region: "Gyeonggi",
        latitude: 37.3370,
        longitude: 126.9670,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── INDIA (13) ────────────────────────────────────────────
    {
        name: "Jawaharlal Nehru Port (Nhava Sheva)",
        code: "INNSA",
        country: "India",
        countryCode: "IN",
        city: "Navi Mumbai",
        region: "Maharashtra",
        latitude: 18.9500,
        longitude: 72.9500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Mundra Port (Adani Ports)",
        code: "INMUN",
        country: "India",
        countryCode: "IN",
        city: "Mundra",
        region: "Gujarat",
        latitude: 22.7500,
        longitude: 69.7000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Chennai",
        code: "INMAA",
        country: "India",
        countryCode: "IN",
        city: "Chennai",
        region: "Tamil Nadu",
        latitude: 13.0827,
        longitude: 80.2707,
        type: LocationType.SEA_PORT,
    },
    {
        name: "V.O. Chidambaranar Port (Tuticorin)",
        code: "INTUT",
        country: "India",
        countryCode: "IN",
        city: "Thoothukudi",
        region: "Tamil Nadu",
        latitude: 8.7533,
        longitude: 78.1811,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Kolkata (Syama Prasad Mookerjee)",
        code: "INCCU",
        country: "India",
        countryCode: "IN",
        city: "Kolkata",
        region: "West Bengal",
        latitude: 22.5333,
        longitude: 88.3167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Cochin International Container Transshipment Terminal",
        code: "INCOK",
        country: "India",
        countryCode: "IN",
        city: "Kochi",
        region: "Kerala",
        latitude: 9.9667,
        longitude: 76.2667,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Visakhapatnam Port",
        code: "INVTZ",
        country: "India",
        countryCode: "IN",
        city: "Visakhapatnam",
        region: "Andhra Pradesh",
        latitude: 17.6868,
        longitude: 83.2185,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Indira Gandhi International Airport Cargo",
        code: "DEL",
        country: "India",
        countryCode: "IN",
        city: "New Delhi",
        region: "Delhi",
        latitude: 28.5562,
        longitude: 77.1000,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Chhatrapati Shivaji Maharaj Cargo Terminal",
        code: "BOM",
        country: "India",
        countryCode: "IN",
        city: "Mumbai",
        region: "Maharashtra",
        latitude: 19.0896,
        longitude: 72.8656,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Kempegowda International Airport Air Cargo",
        code: "BLR",
        country: "India",
        countryCode: "IN",
        city: "Bengaluru",
        region: "Karnataka",
        latitude: 13.1986,
        longitude: 77.7066,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Tughlakabad Inland Container Depot (TKD)",
        code: "INTKD-ICD",
        country: "India",
        countryCode: "IN",
        city: "New Delhi",
        region: "Delhi",
        latitude: 28.5100,
        longitude: 77.2900,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Dadri Inland Container Depot (CONCOR)",
        code: "INDAD-ICD",
        country: "India",
        countryCode: "IN",
        city: "Greater Noida",
        region: "Uttar Pradesh",
        latitude: 28.5500,
        longitude: 77.5600,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Whitefield Inland Container Depot",
        code: "INWFD-ICD",
        country: "India",
        countryCode: "IN",
        city: "Bengaluru",
        region: "Karnataka",
        latitude: 12.9700,
        longitude: 77.7500,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── MIDDLE EAST & WEST ASIA (19) ──────────────────────────
    {
        name: "Jebel Ali Port (DP World)",
        code: "AEJEA",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Dubai",
        region: "Dubai",
        latitude: 25.0112,
        longitude: 55.0617,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Khalifa Port Abu Dhabi",
        code: "AEKHL",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Abu Dhabi",
        region: "Abu Dhabi",
        latitude: 24.8167,
        longitude: 54.6833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Fujairah",
        code: "AEFJR",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Fujairah",
        region: "Fujairah",
        latitude: 25.1833,
        longitude: 56.3667,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Dubai International Airport Cargo Mega Terminal",
        code: "DXB",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Dubai",
        region: "Dubai",
        latitude: 25.2532,
        longitude: 55.3657,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Al Maktoum International Airport (DWC Logistics)",
        code: "DWC",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Dubai",
        region: "Dubai",
        latitude: 24.8967,
        longitude: 55.1614,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Dubai Logistics City Container Depot",
        code: "AEDLC-ICD",
        country: "United Arab Emirates",
        countryCode: "AE",
        city: "Dubai",
        region: "Dubai",
        latitude: 24.9100,
        longitude: 55.1500,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Jeddah Islamic Port",
        code: "SAJED",
        country: "Saudi Arabia",
        countryCode: "SA",
        city: "Jeddah",
        region: "Makkah",
        latitude: 21.4667,
        longitude: 39.1667,
        type: LocationType.SEA_PORT,
    },
    {
        name: "King Abdulaziz Port (Dammam)",
        code: "SADMM",
        country: "Saudi Arabia",
        countryCode: "SA",
        city: "Dammam",
        region: "Eastern Province",
        latitude: 26.4333,
        longitude: 50.1833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "King Khalid International Airport Cargo",
        code: "RUH",
        country: "Saudi Arabia",
        countryCode: "SA",
        city: "Riyadh",
        region: "Riyadh",
        latitude: 24.9576,
        longitude: 46.6988,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Riyadh Dry Port",
        code: "SARUH-ICD",
        country: "Saudi Arabia",
        countryCode: "SA",
        city: "Riyadh",
        region: "Riyadh",
        latitude: 24.6667,
        longitude: 46.7500,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Hamad Port",
        code: "QAHMD",
        country: "Qatar",
        countryCode: "QA",
        city: "Umm Al Houl",
        region: "Al Wakrah",
        latitude: 25.0167,
        longitude: 51.6167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Hamad International Airport Cargo Terminal",
        code: "DOH",
        country: "Qatar",
        countryCode: "QA",
        city: "Doha",
        region: "Doha",
        latitude: 25.2731,
        longitude: 51.6081,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Shuwaikh Port",
        code: "KWSWK",
        country: "Kuwait",
        countryCode: "KW",
        city: "Kuwait City",
        region: "Al Asimah",
        latitude: 29.3500,
        longitude: 47.9167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Kuwait International Cargo Terminal",
        code: "KWI",
        country: "Kuwait",
        countryCode: "KW",
        city: "Farwaniya",
        region: "Farwaniya",
        latitude: 29.2268,
        longitude: 47.9689,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Khalifa Bin Salman Port (Hidd)",
        code: "BHKBS",
        country: "Bahrain",
        countryCode: "BH",
        city: "Hidd",
        region: "Muharraq Governorate",
        latitude: 26.1833,
        longitude: 50.6833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Bahrain International Airport Cargo",
        code: "BAH",
        country: "Bahrain",
        countryCode: "BH",
        city: "Muharraq",
        region: "Muharraq Governorate",
        latitude: 26.2708,
        longitude: 50.6336,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Port of Salalah (APM Terminals)",
        code: "OMSLL",
        country: "Oman",
        countryCode: "OM",
        city: "Salalah",
        region: "Dhofar",
        latitude: 16.9500,
        longitude: 54.0000,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Sohar",
        code: "OMSOH",
        country: "Oman",
        countryCode: "OM",
        city: "Sohar",
        region: "Al Batinah North",
        latitude: 24.4833,
        longitude: 56.6333,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Muscat International Airport Cargo Hub",
        code: "MCT",
        country: "Oman",
        countryCode: "OM",
        city: "Muscat",
        region: "Muscat Governorate",
        latitude: 23.5933,
        longitude: 58.2844,
        type: LocationType.AIR_PORT,
    },

    // ─── SOUTHEAST ASIA (16) ───────────────────────────────────
    {
        name: "Port Klang (Northport & Westports)",
        code: "MYPKG",
        country: "Malaysia",
        countryCode: "MY",
        city: "Port Klang",
        region: "Selangor",
        latitude: 2.9986,
        longitude: 101.3917,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Tanjung Pelepas (PTP)",
        code: "MYTPP",
        country: "Malaysia",
        countryCode: "MY",
        city: "Iskandar Puteri",
        region: "Johor",
        latitude: 1.3667,
        longitude: 103.5500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Kuala Lumpur International Airport Cargo",
        code: "KUL",
        country: "Malaysia",
        countryCode: "MY",
        city: "Sepang",
        region: "Selangor",
        latitude: 2.7456,
        longitude: 101.7099,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Port of Hai Phong (Tan Vu Terminal)",
        code: "VNHPH",
        country: "Vietnam",
        countryCode: "VN",
        city: "Hai Phong",
        region: "Red River Delta",
        latitude: 20.8667,
        longitude: 106.6833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Cai Mep-Thi Vai Deep Sea Terminal",
        code: "VNCMT",
        country: "Vietnam",
        countryCode: "VN",
        city: "Phu My",
        region: "Ba Ria–Vung Tau",
        latitude: 10.5167,
        longitude: 107.0167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Tan Cang Cat Lai Port",
        code: "VNSGN",
        country: "Vietnam",
        countryCode: "VN",
        city: "Ho Chi Minh City",
        region: "Southeast",
        latitude: 10.7600,
        longitude: 106.7900,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Noi Bai International Airport Cargo Terminal",
        code: "HAN",
        country: "Vietnam",
        countryCode: "VN",
        city: "Hanoi",
        region: "Red River Delta",
        latitude: 21.2212,
        longitude: 105.8072,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Song Than Inland Container Depot",
        code: "VNSTH-ICD",
        country: "Vietnam",
        countryCode: "VN",
        city: "Di An",
        region: "Binh Duong",
        latitude: 10.9000,
        longitude: 106.7500,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Laem Chabang Port",
        code: "THLCH",
        country: "Thailand",
        countryCode: "TH",
        city: "Chonburi",
        region: "Eastern Thailand",
        latitude: 13.0833,
        longitude: 100.8833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Suvarnabhumi Airport Cargo Center",
        code: "BKK",
        country: "Thailand",
        countryCode: "TH",
        city: "Bang Phli",
        region: "Samut Prakan",
        latitude: 13.6900,
        longitude: 100.7501,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Lat Krabang Inland Container Depot",
        code: "THLKB-ICD",
        country: "Thailand",
        countryCode: "TH",
        city: "Bangkok",
        region: "Bangkok",
        latitude: 13.7200,
        longitude: 100.7800,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
    {
        name: "Port of Tanjung Priok (Jakarta)",
        code: "IDTPP",
        country: "Indonesia",
        countryCode: "ID",
        city: "Jakarta",
        region: "Special Capital Region of Jakarta",
        latitude: -6.1000,
        longitude: 106.8833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Manila International Container Terminal (MICT)",
        code: "PHMNL",
        country: "Philippines",
        countryCode: "PH",
        city: "Manila",
        region: "Metro Manila",
        latitude: 14.6000,
        longitude: 120.9500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Batangas",
        code: "PHBTG",
        country: "Philippines",
        countryCode: "PH",
        city: "Batangas City",
        region: "Calabarzon",
        latitude: 13.7500,
        longitude: 121.0500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Ninoy Aquino International Airport Cargo",
        code: "MNL",
        country: "Philippines",
        countryCode: "PH",
        city: "Pasay",
        region: "Metro Manila",
        latitude: 14.5086,
        longitude: 121.0194,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Calamba Inland Container Depot",
        code: "PHCLB-ICD",
        country: "Philippines",
        countryCode: "PH",
        city: "Calamba",
        region: "Laguna",
        latitude: 14.2100,
        longitude: 121.1600,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },

    // ─── SOUTH ASIA (6) ────────────────────────────────────────
    {
        name: "Port of Colombo (JCT & CICT)",
        code: "LKCMB",
        country: "Sri Lanka",
        countryCode: "LK",
        city: "Colombo",
        region: "Western Province",
        latitude: 6.9500,
        longitude: 79.8500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port of Hambantota (HIPG)",
        code: "LKHRI",
        country: "Sri Lanka",
        countryCode: "LK",
        city: "Hambantota",
        region: "Southern Province",
        latitude: 6.1167,
        longitude: 81.1167,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Bandaranaike International Airport Cargo",
        code: "CMB",
        country: "Sri Lanka",
        countryCode: "LK",
        city: "Katunayake",
        region: "Western Province",
        latitude: 7.1808,
        longitude: 79.8841,
        type: LocationType.AIR_PORT,
    },
    {
        name: "Port of Karachi (SAPT & KICT)",
        code: "PKKHI",
        country: "Pakistan",
        countryCode: "PK",
        city: "Karachi",
        region: "Sindh",
        latitude: 24.8333,
        longitude: 66.9833,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Port Muhammad Bin Qasim",
        code: "PKBQM",
        country: "Pakistan",
        countryCode: "PK",
        city: "Karachi",
        region: "Sindh",
        latitude: 24.7833,
        longitude: 67.3500,
        type: LocationType.SEA_PORT,
    },
    {
        name: "Lahore Mughalpura Dry Port",
        code: "PKLHE-ICD",
        country: "Pakistan",
        countryCode: "PK",
        city: "Lahore",
        region: "Punjab",
        latitude: 31.5700,
        longitude: 74.3700,
        type: LocationType.INLAND_CONTAINER_DEPOT,
    },
];

async function main() {
    console.log(`🌱 [Seed] Starting location seed with ${genuineLocations.length} genuine locations...`);

    // Verify all codes are unique
    const seenCodes = new Set<string>();
    for (const loc of genuineLocations) {
        if (seenCodes.has(loc.code)) {
            throw new Error(`Duplicate code detected in seed data: ${loc.code}`);
        }
        seenCodes.add(loc.code);
    }

    let createdCount = 0;
    let updatedCount = 0;

    // Process in batches of 25 with upsert to guarantee idempotency and avoid duplicates
    const BATCH_SIZE = 25;
    for (let i = 0; i < genuineLocations.length; i += BATCH_SIZE) {
        const batch = genuineLocations.slice(i, i + BATCH_SIZE);

        await Promise.all(
            batch.map(async (location) => {
                const existing = await prisma.location.findUnique({
                    where: { code: location.code },
                });

                if (existing) {
                    await prisma.location.update({
                        where: { code: location.code },
                        data: {
                            name: location.name,
                            country: location.country,
                            countryCode: location.countryCode,
                            city: location.city,
                            region: location.region,
                            latitude: location.latitude,
                            longitude: location.longitude,
                            type: location.type,
                            isBlocked: false,
                            isDeleted: false,
                        },
                    });
                    updatedCount++;
                } else {
                    await prisma.location.create({
                        data: {
                            name: location.name,
                            code: location.code,
                            country: location.country,
                            countryCode: location.countryCode,
                            city: location.city,
                            region: location.region,
                            latitude: location.latitude,
                            longitude: location.longitude,
                            type: location.type,
                            isBlocked: false,
                            isDeleted: false,
                        },
                    });
                    createdCount++;
                }
            })
        );

        console.log(`📦 Processed ${Math.min(i + BATCH_SIZE, genuineLocations.length)} / ${genuineLocations.length} locations...`);
    }

    // Invalidate Redis list caches so frontend receives the newly seeded locations immediately
    try {
        const listKeys = await redis.keys("location:list:*");
        const searchKeys = await redis.keys("location:search:*");
        const allKeys = [...listKeys, ...searchKeys];
        if (allKeys.length > 0) {
            await redis.del(...allKeys);
            console.log(`🧹 Invalidated ${allKeys.length} location cache entries in Redis.`);
        }
    } catch (cacheErr) {
        console.warn("⚠️ Redis cache invalidation skipped:", cacheErr);
    }

    console.log(`
🎉 [Seed Complete]
────────────────────────────────────────
Total Locations in Seed : ${genuineLocations.length}
Newly Created           : ${createdCount}
Updated/Verified        : ${updatedCount}
────────────────────────────────────────
`);
}

main()
    .catch((e) => {
        console.error("❌ Seeding failed:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
